### ISSUE TITLE
Unexpected argument `$0~/parsing/'`

### ISSUE THREAD

**Issue by bartoszluka** [mrcjkb/neotest-haskell#75]
### Neovim version (nvim -v)

v0.9.0-dev-1347+gfd32a9875

### Operating system/version

Arch btw

### How to reproduce the issue

1. go to Spec.hs
2. place cursor on the first line of tests (`describe "parsing" $ do`)
3. run `lua require("neotest").run.run()`
4. get the following error
```ghci
seal> test (suite: seal-test, args: -p $0~/parsing/)

seal-test: unexpected argument `$0~/parsing/'
Try `seal-test --help' for more information.

seal> Test suite seal-test failed
Test suite failure for package seal-0.1.0.0
    seal-test:  exited with: ExitFailure 1
Logs printed to console
```
source code:
https://github.com/bartoszluka/seal/blob/aafef2ea9590db3dd77053e17eee1f5b05b40b55/test/Spec.hs#L56

### Expected behaviour

Expect command to be correct: `stack test --match ...`

### Actual behaviour

Weird `$0` in the command. Also if the tests are nested it looks like this:
```ghci
seal> test (suite: seal-test, args: -p $0~/parsing/&&/program/)

seal-test: unexpected argument `$0~/parsing/&&/program/'
Try `seal-test --help' for more information.
```

### A minimal Neovim config used to reproduce this issue.

```lua
-- using lazy.nvim as a package manager
-- this is in the file neotest.lua
return {
    "nvim-neotest/neotest",
    dependencies = {
        "mrcjkb/neotest-haskell",
        "nvim-lua/plenary.nvim",
        "nvim-treesitter/nvim-treesitter",
        "antoinemadec/FixCursorHold.nvim",
    },
    cmd = "NeotestRun",
    config = function()
        require("neotest").setup({
            adapters = {
                require("neotest-haskell"),
            },
        })
    end,
}
```

**Comment by bartoszluka** [comment]
I fixed it by using only hspec in frameworks list.
```lua
-- using lazy.nvim as a package manager
-- this is in the file neotest.lua
return {
    "nvim-neotest/neotest",
    dependencies = {
        "mrcjkb/neotest-haskell",
        "nvim-lua/plenary.nvim",
        "nvim-treesitter/nvim-treesitter",
        "antoinemadec/FixCursorHold.nvim",
    },
    config = function()
        require("neotest").setup({
            adapters = {
                require("neotest-haskell"){
                   frameworks={"hspec"}
                   }
            },
        })
    end,
}

**Comment by bartoszluka** [comment]
Yes, I am using 0.8.0 version. I didn't have any mention of "tasty" in the project so I don't know why it was picked up.

**Comment by mrcjkb** [comment]
Do you have any other projects that use tasty?

I'm asking in case the tree-sitter parser somehow got the contents from the wrong file and cached them.

**Comment by bartoszluka** [comment]
no I haven't heard of tasty before this issue, but I'm converting this very project to tasty now

**Comment by mrcjkb** [comment]
That'll hopefully solve it 😁

Please let me know if you run into any issues.
