### ISSUE TITLE
tasty-golden goldenVsString query missing

### ISSUE THREAD

**Issue by shinzui** [mrcjkb/neotest-haskell#96]
### Neovim version (nvim -v)

v0.9.1

### Operating system/version

macOS

### How to reproduce the issue

Golden tests using [goldenVsString](https://hackage.haskell.org/package/tasty-golden-2.3.5/docs/Test-Tasty-Golden.html#v:goldenVsString) are not detected. It looks like [queries/haskell/tasty-positions.scm](https://github.com/mrcjkb/neotest-haskell/blob/5cded2eee7c170933206d7521bb310af25886843/queries/haskell/tasty-positions.scm) is missing a query for that function. 

### Expected behaviour

Running the golden test. 

### Actual behaviour

The test is not detected. 

### A minimal Neovim config used to reproduce this issue.

Not applicable.

**Comment by mrcjkb** [comment]
Thanks for reporting this :smile:

**Comment by mrcjkb** [comment]
@all-contributors please add @shinzui  for bug

**Comment by shinzui** [comment]
Thank you @mrcjkb for fixing it so quickly.
